// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/about" | "/admin/blogs" | "/admin/blogs/new" | "/admin/careers" | "/admin/careers/[id]/applications" | "/admin/careers/new" | "/admin/case-studies" | "/admin/case-studies/[id]" | "/admin/chat" | "/admin/cta" | "/admin/docs" | "/admin/docs/[id]/edit" | "/admin/docs/new" | "/admin/faqs" | "/admin/faqs/[id]/edit" | "/admin/faqs/new" | "/admin/hero" | "/admin/leads" | "/admin/leads/[id]" | "/admin/legal" | "/admin/legal/[slug]" | "/admin/newsletter" | "/admin/our-story" | "/admin/our-story/[id]" | "/admin/our-story/new" | "/admin/posts" | "/admin/posts/[id]" | "/admin/pricing" | "/admin/pricing/new" | "/admin/projects" | "/admin/projects/new" | "/admin/services" | "/admin/services/[id]" | "/admin/settings" | "/admin/solutions" | "/admin/solutions/[id]" | "/admin/stats" | "/auth/signin" | "/blog" | "/blog/[slug]" | "/careers" | "/careers/[id]/apply" | "/careers/success" | "/case-studies" | "/case-studies/[slug]" | "/checkout/[planId]" | "/code/[slug]" | "/contact" | "/dashboard" | "/dashboard/analytics" | "/dashboard/billing" | "/dashboard/leads" | "/dashboard/settings" | "/dashboard/training" | "/demo/[slug]" | "/landing" | "/legal/[slug]" | "/our-story" | "/pricing" | "/projects/[slug]" | "/solutions" | "/solutions/[slug]" | "/stories"
type AppRouteHandlerRoutes = "/api/auth/[...nextauth]" | "/api/chat" | "/api/contact" | "/api/register"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/about": {}
  "/admin/blogs": {}
  "/admin/blogs/new": {}
  "/admin/careers": {}
  "/admin/careers/[id]/applications": { "id": string; }
  "/admin/careers/new": {}
  "/admin/case-studies": {}
  "/admin/case-studies/[id]": { "id": string; }
  "/admin/chat": {}
  "/admin/cta": {}
  "/admin/docs": {}
  "/admin/docs/[id]/edit": { "id": string; }
  "/admin/docs/new": {}
  "/admin/faqs": {}
  "/admin/faqs/[id]/edit": { "id": string; }
  "/admin/faqs/new": {}
  "/admin/hero": {}
  "/admin/leads": {}
  "/admin/leads/[id]": { "id": string; }
  "/admin/legal": {}
  "/admin/legal/[slug]": { "slug": string; }
  "/admin/newsletter": {}
  "/admin/our-story": {}
  "/admin/our-story/[id]": { "id": string; }
  "/admin/our-story/new": {}
  "/admin/posts": {}
  "/admin/posts/[id]": { "id": string; }
  "/admin/pricing": {}
  "/admin/pricing/new": {}
  "/admin/projects": {}
  "/admin/projects/new": {}
  "/admin/services": {}
  "/admin/services/[id]": { "id": string; }
  "/admin/settings": {}
  "/admin/solutions": {}
  "/admin/solutions/[id]": { "id": string; }
  "/admin/stats": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/chat": {}
  "/api/contact": {}
  "/api/register": {}
  "/auth/signin": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/careers": {}
  "/careers/[id]/apply": { "id": string; }
  "/careers/success": {}
  "/case-studies": {}
  "/case-studies/[slug]": { "slug": string; }
  "/checkout/[planId]": { "planId": string; }
  "/code/[slug]": { "slug": string; }
  "/contact": {}
  "/dashboard": {}
  "/dashboard/analytics": {}
  "/dashboard/billing": {}
  "/dashboard/leads": {}
  "/dashboard/settings": {}
  "/dashboard/training": {}
  "/demo/[slug]": { "slug": string; }
  "/landing": {}
  "/legal/[slug]": { "slug": string; }
  "/our-story": {}
  "/pricing": {}
  "/projects/[slug]": { "slug": string; }
  "/solutions": {}
  "/solutions/[slug]": { "slug": string; }
  "/stories": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
