// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/admin/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/about">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/blogs/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blogs/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/blogs/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/blogs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blogs">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/blogs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/careers/[id]/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/careers/[id]/applications">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/careers/[id]/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/careers/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/careers/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/careers/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/careers">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/case-studies/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/case-studies/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/case-studies/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/case-studies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/case-studies">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/case-studies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/cta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cta">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/cta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/docs/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/docs/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/docs/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/docs/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/docs/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/docs/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/docs">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/faqs/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/faqs/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/faqs/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/faqs/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/faqs/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/faqs/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/faqs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/faqs">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/faqs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/hero/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/hero">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/hero/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/leads/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/leads/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/leads/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/leads">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/legal/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/legal/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/legal/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/legal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/legal">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/legal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/newsletter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/newsletter">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/newsletter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/our-story/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/our-story/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/our-story/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/our-story/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/our-story/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/our-story/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/our-story/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/our-story">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/our-story/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/posts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/posts/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/posts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/posts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/posts">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/posts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/pricing/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pricing/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/pricing/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/projects/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/projects/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/projects/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/projects">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/services/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/services/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/services/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/services">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/solutions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/solutions/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/solutions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/solutions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/solutions">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/solutions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signin">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/careers/[id]/apply/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers/[id]/apply">> = Specific
  const handler = {} as typeof import("../../../src/app/careers/[id]/apply/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../../src/app/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/careers/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers/success">> = Specific
  const handler = {} as typeof import("../../../src/app/careers/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/case-studies/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/case-studies/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/case-studies/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/case-studies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/case-studies">> = Specific
  const handler = {} as typeof import("../../../src/app/case-studies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/checkout/[planId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout/[planId]">> = Specific
  const handler = {} as typeof import("../../../src/app/checkout/[planId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/code/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/code/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/code/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leads">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/training/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/training">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/training/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/demo/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/demo/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing">> = Specific
  const handler = {} as typeof import("../../../src/app/landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/legal/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/legal/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/our-story/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/our-story">> = Specific
  const handler = {} as typeof import("../../../src/app/our-story/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/projects/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/projects/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/solutions/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/solutions/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/solutions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions">> = Specific
  const handler = {} as typeof import("../../../src/app/solutions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/stories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stories">> = Specific
  const handler = {} as typeof import("../../../src/app/stories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/register">> = Specific
  const handler = {} as typeof import("../../../src/app/api/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
