"use server";

import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";

export async function subscribe(formData: FormData) {
    const email = formData.get("email") as string;

    if (!email || !email.includes("@")) {
        return { error: "Invalid email address" };
    }

    try {
        // @ts-ignore
        await prisma.newsletterSubscriber.create({
            data: { email }
        });
        return { success: true };
    } catch (error) {
        // Unique constraint failed
        return { error: "Email already subscribed" };
    }
}

export async function getSubscribers() {
    // @ts-ignore
    const subscribers = await prisma.newsletterSubscriber.findMany({
        orderBy: { subscribedAt: 'desc' }
    });

    const users = await prisma.user.findMany({
        where: { email: { not: null } },
        select: { email: true, createdAt: true, id: true }
    });

    // Combine and deduplicate by email
    const allEmails = new Map();

    // Add subscribers first
    subscribers.forEach((sub: any) => {
        allEmails.set(sub.email, { ...sub, type: 'subscriber' });
    });

    // Add registered users (if not already subscribed)
    users.forEach((user) => {
        if (!allEmails.has(user.email)) {
            allEmails.set(user.email, {
                id: user.id,
                email: user.email,
                subscribedAt: user.createdAt,
                type: 'user'
            });
        }
    });

    return Array.from(allEmails.values()).sort((a: any, b: any) =>
        new Date(b.subscribedAt).getTime() - new Date(a.subscribedAt).getTime()
    );
}

export async function generateAiNewsletter() {
    // Simulate AI Generation with "Tech Trends"
    const topics = [
        "The Rise of Autonomous AI Agents",
        "Quantum Computing: Is it ready?",
        "Blockchain vs Traditional Databases",
        "The Future of React and Server Components",
        "Cybersecurity in the Age of AI"
    ];

    const randomTopic = topics[Math.floor(Math.random() * topics.length)];

    const subject = `Daily Tech Update: ${randomTopic}`;
    const content = `
Hello Tech Enthusiast,

Here is your daily dose of technology insights generated by our AI engine.

## ${randomTopic}

The world of technology is moving fast. Today we are seeing significant breakthroughs in ${randomTopic.toLowerCase()}. 
Key takeaways for developers and businesses include:

1. Increased efficiency in automated workflows.
2. New paradigms for data security.
3. Enhanced user experiences through predictive interfaces.

Stay tuned for tomorrow's update on emerging frameworks.

Best,
The StarApp.AI Team
    `.trim();

    // specific delay to simulate "AI Thinking"
    await new Promise(resolve => setTimeout(resolve, 2000));

    return { subject, content };
}

export async function sendNewsletter(formData: FormData) {
    const subject = formData.get("subject");
    const content = formData.get("content");

    // Simulate sending email (would integrate Resend/SendGrid here)
    // console.log("Sending Newsletter:", { subject, content });

    await new Promise(resolve => setTimeout(resolve, 1000));

    return { success: true, count: 1534 }; // Mock count
}
